### ISSUE TITLE
Ref support

### ISSUE THREAD

**Issue by maxmert** [elowes/react-blocks-scroll-sync#1]
Hi and thanks for your components.

Currently because of https://github.com/elowes/react-blocks-scroll-sync/blob/master/src/components/Block/index.tsx#L36 injection if you're passing `ref` to `Block`, you get Jss instance. Currently there are not much styles for injection, mb better will be to return Block instance instead?

Thanks in advance.

Best wishes,
Max

**Comment by hellohejinyu** [comment]
Thanks for your advice. Already publish npm `1.1.0`.
